
[theme]
base="light"
primaryColor="#ff3131"               # Bold maple red
backgroundColor="#fafcfe"            # Almost white, cool and clean (like snow in sunlight ❄️)
secondaryBackgroundColor="#edf1f7"   # Very soft contrast — clean but not flat
textColor="#111111"                  # Strong contrast, not harsh
font="monospace"                     # Still keeping the hacker/synth feel