
[theme]
base="dark"
primaryColor="#ff3131"               # Maple-leaf red (for buttons, links, accents)
backgroundColor="#0f0f1a"            # Cyberpunk black-blue background
secondaryBackgroundColor="#1f1f2e"   # Slight contrast for cards/containers
textColor="#00ff99"                  # Neon green (for all text elements)
font="monospace"                     # Futuristic/console feel